### ISSUE TITLE
Components are in blank

### ISSUE THREAD

**Issue by jrmartinez96** [apipemc/jspdf-react#4]
I tried using thin library, to test I used the exact example shown in the readme. But all I see is a blank pdf, can someone help me? The only component that renders in the pdf preview is Text.

**Comment by iozzyi** [comment]
Tried this library as well, does not render anything from the example in the readme

**Comment by jrmartinez96** [comment]
Exactly. Try the example from the example folder, it worked for me after all. At the end I found this library with a lot of limitations, so I used the jspdf library directly and it was much easier.
